/**
 * model/Constantes.java
 *
 * File generated from the Constantes uml Interface
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 2/26/14 2:00:37 PM (February 26, 2014) $
 */
package data;

// Start of user code to add imports for Constantes
 

// End of user code

/**
 * Description of the interface Constantes.
 *
 */

public interface Constantes {
    public int CAPACITE_CASE = 10;
    public int CAPACITE_RECOLTEUR = 100;
    public int HAUTEUR = 30;
    public int LARGEUR = 30;
	
	// Start of user code to add fields for Constantes
 
	// End of user code

	// Start of user code to add methods for Constantes
 
	// End of user code
}