/**
* model/Ressource.java
*
* File generated from the Ressource uml Class
* Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
* $ Date : 2/26/14 2:00:36 PM (February 26, 2014) $
*/
package environment;

// Start of user code to add imports for Ressource


// End of user code

/**
* Description of the class Ressource.
*
*/

public class Ressource{
    private int quantite;
    private TypeRessource typeRessource;

    // Start of user code to add fields for Ressource

    // End of user code

    /**
     * Constructor.
     */
    public Ressource(int quantite, TypeRessource type) {
        // Start of user code for constructor Ressource
        super();
        this.quantite = quantite;
        this.typeRessource = type;
        // End of user code
    }

    /**
     * Return quantite.
     * @return quantite
     */
    public int getQuantite() {
        return quantite;
    }

    /**
     * Set a value to attribute quantite.
     * @param n
     */
    public void decrementerQuantite(int n) {
        if (quantite -n < 0)
            quantite = 0;
        else
            quantite -= n;
    }

    /**
     * Return typeRessource.
     * @return typeRessource
     */
    public TypeRessource getTypeRessource() {
        return typeRessource;
    }


    /**
     * Description of the method estVide.
     *
     * @return ret
     */
    public boolean estVide() {
        // Start of user code for method estVide
        return quantite == 0;
        // End of user code
    }

    // Start of user code to add methods for Ressource

    // End of user code
}