/**
 * model/TypeRessource.java
 *
 * File generated from the TypeRessource uml Enumeration
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 2/26/14 2:00:37 PM (February 26, 2014) $
 */
package environment;

/**
 * Description of the enumeration TypeRessource.
 *
 */

public enum TypeRessource {
    BOIS,
    NOURRITURE
}