/**
 * model/IUniteLibre.java
 *
 * File generated from the IUniteLibre uml Interface
 * Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
 * $ Date : 2/26/14 2:00:37 PM (February 26, 2014) $
 */
package agents;

// Start of user code to add imports for IUniteLibre
 

// End of user code

import environment.Case;

/**
 * Description of the interface IUniteLibre.
 *
 */

public interface IUniteLibre {
	
	// Start of user code to add fields for IUniteLibre
 
	// End of user code

    /**
     *  Description of the method seDeplacer.
     *
     *
     * @param caseLibre
     */
    public void seDeplacer(Case caseLibre);

    /**
     *  Description of the method seDeplacer.
     *
     *
     * @param cible
     */
    public void suivreUnite(IAgent cible);



	// Start of user code to add methods for IUniteLibre
 
	// End of user code
}