/**
* model/Unite.java
*
* File generated from the Unite uml Class
* Generated by the Acceleo UML 2.1 to Java generator module (Obeo)
* $ Date : 2/26/14 2:00:36 PM (February 26, 2014) $
*/
package agents;

// Start of user code to add imports for Unite


// End of user code

import environment.Carte;
import environment.Case;

import java.awt.*;

/**
* Description of the class Unite.
*
*/

public class Unite extends Agent implements IAgent{
    protected int pointAction;
    protected double porteeAction;
    protected double porteeVision;
    // End of user code

    /**
     * Constructor.
     */
    public Unite(Base b, int pv, int pa, double poa, double pov, Case<Point> c, Carte ca) {
        // Start of user code for constructor Unite
        super(pv, c, ca);
        this.maBase = b;
        this.pointAction = pa;
        this.porteeAction = poa;
        this.porteeVision = pov;
        // ajout de l'unité dans sa case
        c.ajouterUnite(this);
        // End of user code
    }

    /**
     * Return maBase.
     * @return maBase
     */
    public Base getBase() {
        return this.maBase;
    }

    public void subirDegats(int degats) {
        super.subirDegats(degats);
        if(getPvRestant() == 0) {
            //System.out.println("une unite de " + getBase().getNom() + " est morte.");
            getCase().retirerUnite(this);
        }
    }

    public void reagir() {

    }

    // End of user code
}